import type { Metadata } from "next";
import { Poppins, Inter } from "next/font/google";
import { Container, Flex } from "@radix-ui/themes";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700"],
  variable: "--font-poppins",
});

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} ${inter.variable}`}>
      <body className="bg-ebony-clay/99">
        <main className="max-w-6xl mx-auto">
          <Container>{children}</Container>
        </main>
      </body>
    </html>
  );
}
