import { Container, Theme, ThemePanel } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import NavBar from "../components/NavBar";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700"],
  variable: "--font-poppins",
});

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Joeffrey Pilar Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} ${inter.variable}`}>
      <body className="">
        <Theme
          className="!bg-ebony-clay !text-white !font-inter"
          accentColor="gray"
        >
          {/* <ThemePanel /> */}
          <NavBar />
          <main className=" max-w-6xl mx-auto">
            <Container p="2">{children}</Container>
          </main>
        </Theme>
      </body>
    </html>
  );
}
